version: '3'
services:
  tizen:
    privileged: true
    build: 
      context: tizen-ide
      args:
        ### user config ###
        - ROOT_PASS=${ROOT_PASS}
        - TIZEN_USER=${TIZEN_USER}
        - TIZEN_UID=${TIZEN_UID}
        - TIZEN_GID=${TIZEN_GID}
        ### audio config ###
        - AUDIO_GID=${AUDIO_GID}
        ### version config ###
        - TIZEN_VERSION=${TIZEN_VERSION}
        # - TIZEN_BINARY=web-ide_Tizen_Studio_${TIZEN_VERSION}_ubuntu-64.bin
        - TIZEN_BINARY=web-cli_Tizen_Studio_${TIZEN_VERSION}_ubuntu-64.bin
        - TIZEN_REPO=http://download.tizen.org/sdk/Installer/tizen-studio_${TIZEN_VERSION}
        ### tizen target ###
        - TIZEN_TARGET=${TIZEN_TARGET}
        ### google chrome ###
        - CHROME_REPO=https://dl.google.com/linux/direct
        - CHROME_BINARY=google-chrome-stable_current_amd64.deb
    container_name: tizen-ide
    environment:
      # X11 config
      - XSOCK=${XSOCK}
      - DISPLAY=${DISPLAY}
    volumes:
      - "${XSOCK}:${XSOCK}"
      - "${LOCAL_WORKSPACE}:${DOCKER_WORKSPACE}"
    devices:
      - /dev/snd